server: 
  ssl: 
    enabled: true
    key-store: keystore.p12
    key-store-password: manager
    key-store-type: PKCS12
    key-alias: bns-ssl
  http2:
    enabled: true
  port: 9090
  
  servlet:     context-path: /api/bears

spring: 
  banner: 
    location: classpath:/banner.txt
      
  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet: 
    multipart: 
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      
  resources: 
    add-mappings: false
  mvc: 
    dispatch-options-request: true
    throw-exception-if-no-handler-found: true
    
 
  # MySQL 서버 데이터베이스 지정
  datasource: 
    url: jdbc:mysql://70.12.246.106:3306/ssafy?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://70.12.246.64:3306/ssafy?serverTimezone=UTC
    username: root
    password: manager
    #password: ssafy
    initialization-mode: always
  
  jackson:
    default-property-inclusion: NON_NULL
   
  # JPA
  jpa: 
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true
    show-sql: false
    
  devtools:
    restart:
      additional-paths: .
    livereload:
      enabled: true
      
  freemarker:
    cache: false
      
  thymeleaf: 
    prefix: classpath:/static/
  
# logback Setting
# logging.config=classpath:logback/logback-spring.xml
