server: 
  port: 9090

database: mysql

spring:
  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet: 
    multipart: 
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
 
  # MySQL 서버 데이터베이스 지정
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/ssafy?serverTimezone=UTC
    username: root
    password: manager
    initialization-mode: always
  
  # JPA
  jpa: 
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: true
    show-sql: true
    
  devtools:
    restart:
      additional-paths: .
    livereload:
      enabled: true
      
  freemarker:
    cache: false
      
  thymeleaf: 
    prefix: classpath:/static/
  

# logback Setting
# logging.config=classpath:logback/logback-spring.xml
