spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  
  jackson:
    default-property-inclusion: NON_NULL

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect